/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account; the password is argon2id-hashed, never stored.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, set the session cookie, return the account.
         *
         *     Every failure — unknown email, wrong password, rate-limit lockout —
         *     is the same generic 401 (AR29, no user enumeration). The limiter key
         *     uses the NORMALIZED email (the same form the store compares), so
         *     case-rotating ``DM@example.com`` / ``dm@example.com`` cannot mint
         *     fresh attempt budgets (review round 1). Only failures consume quota —
         *     five legit logins never lock a user out.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the session immediately and clear the cookie; idempotent.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated account.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Own
         * @description The caller's campaigns, oldest first, cursor-paginated.
         */
        get: operations["list_own_api_campaigns_get"];
        put?: never;
        /**
         * Create
         * @description Create a private world owned by the caller (AR27, AD-9).
         */
        post: operations["create_api_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Themes
         * @description The themes a campaign may carry — registered before the
         *     ``/{campaign_id}`` route so the literal path wins the match.
         */
        get: operations["list_themes_api_campaigns_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kinds
         * @description The kinds registry (AD-34): renders ``EDGE_KIND_RULES`` + counter
         *     semantics + dial tables + archetypes, derived from code constants
         *     under a content-hash version token. Registered before the
         *     ``/{campaign_id}`` route so the literal path wins the match. The
         *     endpoint owns no vocabulary and nothing writes it at runtime;
         *     pickers re-fetch per walk mount and commit live-validates.
         */
        get: operations["kinds_api_campaigns_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One
         * @description One owned campaign — foreign/unknown is a single 404 (no oracle).
         */
        get: operations["get_one_api_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description AR20 total hard delete — requires an explicit confirmation body.
         *
         *     Frozen contract (spec-1.6): ``DELETE`` with a JSON body
         *     ``{"confirm": true}``; missing/false confirm -> 400, nothing deleted.
         *     The body is echoed via ``request`` (FastAPI cannot bind a Pydantic
         *     body to DELETE directly) and malformed JSON is a 400. Ownership is
         *     checked FIRST: a foreign id is always 404, even without the confirm
         *     body (matrix row DELETE_FOREIGN).
         */
        delete: operations["delete_api_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description Update seed fields of an owned campaign (PATCH semantics).
         */
        patch: operations["update_api_campaigns__campaign_id__patch"];
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo
         * @description AD-2: undo ONE revision as a compensating commit — 204, no body.
         *
         *     The frozen contract: an absent body undoes the latest revision, a JSON
         *     object body may name the target with ``{"revision_id": "<ulid>"}``,
         *     and anything else present is a 400 (malformed JSON or a non-object
         *     body, the entities.py hand-parse pattern). Ownership is checked FIRST:
         *     a foreign/unknown campaign is the single indistinguishable 404, even
         *     with a malformed body. A campaign with no revision at all is a 404
         *     ("No revision to undo.") — there is nothing to compensate; any other
         *     revision than the head is the store's ``StaleRevisionError`` -> 409
         *     through the shared mapper (rebase-or-reject, never a silent
         *     overwrite), exactly like the other commit routes.
         *
         *     Undo appends its own revision (the log is never rewritten). Media
         *     rows are never RESTORED by undo (``store/undo.py``, spec-4.3); when
         *     the undo DELETES an entity — the inverse of an entity-CREATION
         *     revision — its manifest rows are reclaimed inside the store
         *     transaction and the FILES are reclaimed post-commit here, the
         *     delete-entity route's rows-first pattern (AD-10).
         */
        post: operations["undo_api_campaigns__campaign_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revisions History
         * @description The Tonight recent-changes read (AD-35): read-only, owner-gated,
         *     bounded (default 20, clamped to max 100), newest first. Summaries
         *     are display-ready ``{revision_id, created_at, actor, action,
         *     target_names, kind}``; verb commits and their take-backs both map
         *     to ``edited`` (AD-27 — the feed never distinguishes undo from
         *     edit). Unknown/foreign campaign is the single 404 (no oracle).
         */
        get: operations["revisions_history_api_campaigns__campaign_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/run-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run State
         * @description The Tonight Tier-2 read (AD-26, AD-28): current run-state rows
         *     behind the log, owner-gated, read-only — readers stay dumb (the
         *     store owns the state; this endpoint renders the rows, nothing
         *     more). Never exports (AD-11 untouched: the exporter reads
         *     entity/edge only) and never writes. Unknown/foreign campaign is
         *     the single 404 (no oracle). Rows ordered by rowid (commit) order
         *     per AD-16.
         */
        get: operations["run_state_api_campaigns__campaign_id__run_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/generic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Generic
         * @description Create-or-get the caller's Generic library world (owner spec,
         *     2026-09-17): the per-account storage context for characters generated
         *     without a canon world. Idempotent — the same world returns for every
         *     call regardless of theme (the theme rides each generation job).
         */
        post: operations["ensure_generic_api_campaigns_generic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Character
         * @description Move one character out of the Generic library into this canon
         *     world: a fresh-ULID copy commits here and the library row leaves
         *     (its library edges cascade away — they named library rows, not this
         *     world). Ownership on both campaigns (AD-9); source must be the
         *     Generic library, target must not be.
         */
        post: operations["move_character_api_campaigns__campaign_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return the service health status.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaign Jobs
         * @description Campaign-scoped FIFO list, oldest first, cursor-paginated (AD-9).
         *
         *     Ownership (spec-6-4): the ownership 404 fires before cursor decoding
         *     — a stranger learns nothing, not even via the cursor error surface.
         */
        get: operations["list_campaign_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Enqueue a job at the FIFO tail; idempotent by job_id (AD-3, AR28).
         *
         *     Ownership (spec-6-4): the caller's session must own the campaign —
         *     foreign and unknown campaigns are the same 404 raised BEFORE the
         *     store ever runs (the characters ``_require_campaign`` precedent).
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description One job plus its current queue position (STATUS_POSITION).
         *
         *     Ownership (spec-6-4): there is no campaign_id to gate on, so the
         *     route resolves the job first (store is owner-blind, AD-3), then gates
         *     its campaign — a foreign job's 404 is byte-identical to a genuinely
         *     unknown job's (``_require_owned_job``, no-oracle rule).
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job Route
         * @description Cancel a queued or running job; frees the queue slot (AR28).
         *
         *     Ownership (spec-6-4): the ownership check runs BEFORE any mutation —
         *     a foreign cancel is a byte-identical 404 and the job's state and row
         *     are untouched (resolve-then-gate, then cancel).
         */
        post: operations["cancel_job_route_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Entity
         * @description FR4/AD-5: delete one entity through the store's commit path.
         */
        delete: operations["delete_entity_api_campaigns__campaign_id__entities__entity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Entity
         * @description FR10/spec-3.6: hand-edit one committed entity through the store's
         *     commit path — the DM is the final author.
         *
         *     Partial fields (identity anchor, lore sections, ``stat_block``,
         *     ``world_integration``, ``boss``, ``text``, unknown keys) merge onto
         *     the current record and commit as exactly one ``entity_updated``
         *     revision; a value-identical PATCH commits none (204, idempotent).
         *     ``base_revision`` is opt-in optimistic concurrency (omitted targets
         *     the current head, resolved inside the store call; a moved head is a
         *     409 ``StaleRevisionError`` — rebase-or-reject). Shape validation is
         *     conditional (owner decision 2026-09-05): shape-valid records must
         *     stay shape-valid (422 naming the break, zero revisions); bare
         *     records merge unconstrained.
         *
         *     AD-29 bundled save: ``knowledge_flips`` (a list of ``{"field",
         *     "known"}`` over the closed secret/rumor/party_hook set) is NOT a
         *     record key — it is extracted before the merge and rides the SAME
         *     revision as the edit (one save = one undoable step whose take-back
         *     inverts both halves). A flip-only PATCH (no other content key) is
         *     legal — the store commits the knowledge-only revision. Malformed
         *     ``knowledge_flips`` (non-list, non-object item, non-string field,
         *     non-boolean known) is a 422 with zero revisions.
         *
         *     Ownership-404-first, mirroring ``delete_entity``: the campaign check
         *     runs BEFORE any body is read, so a foreign/unknown campaign is the
         *     single indistinguishable 404 even with a malformed body. The body is
         *     therefore hand-parsed (pydantic body parameters would validate — and
         *     422 — before the handler ran); malformed/non-object/absent body is a
         *     400, ``base_revision`` non-string is a 400, and a body whose only
         *     key is ``base_revision`` is a 400 (at least one content key is
         *     required). 204 body-less, the DELETE precedent.
         */
        patch: operations["update_entity_api_campaigns__campaign_id__entities__entity_id__patch"];
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/session-verb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session Verb
         * @description One Tier-2a consequence verb as ONE undoable revision (AD-26,
         *     AD-28) — the Tonight verb-row wire surface (spec-v3-tier2-routes).
         *
         *     Body ``{"update": {…}, "base_revision"?: str}``: ``update`` is the
         *     verb's delta, a strict-JSON object the store MERGES onto the
         *     entity's current session-state image and commits in full
         *     (rebuild-faithful, AD-26). The four UX verbs (defeated /
         *     allegiance / thread / item) are UI affordances over this open image
         *     — the image itself is open (the AD-27 scar ``{"hp": -12}`` is a
         *     verb in the take-back tests); no closed verb set at the wire.
         *
         *     204 body-less, the undo/PATCH precedent — the UI re-reads state
         *     from the feed and run-state. A value-identical merge (the double-
         *     fire of a repeated gesture) commits nothing and still 204s (the
         *     store's no-op, AD-26/Flow 6). Ownership-404-first: a foreign or
         *     unknown campaign is the single indistinguishable 404 before any
         *     body read; malformed/non-object body is a 400; missing or
         *     non-object ``update`` and a non-string ``base_revision`` are 422 —
         *     the store's ``InvalidRunStateError``/``StaleRevisionError``/
         *     ``UnknownEntityError`` map through the shared mapper (422/409/404).
         */
        post: operations["session_verb_api_campaigns__campaign_id__entities__entity_id__session_verb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/knowledge-toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Knowledge Toggle
         * @description One Tier-2b party-knowledge toggle as its own undoable step
         *     (AD-29) — flippable secret <-> known either direction at any time.
         *
         *     Body ``{"field": "secret"|"rumor"|"party_hook", "known": bool,
         *     "base_revision"?: str}`` — the DM's gesture IS the target state
         *     (absolute set, never a flip-relative toggle). ``known: 1``/``0``
         *     are 422s here and at the store (strict bool contract). The closed
         *     field set is the store's + the DB CHECK, so a foreign field is the
         *     store's 422 through the shared mapper.
         *
         *     204 body-less (the verb precedent); a repeated same-value flip
         *     commits nothing (store no-op) and still 204s. Ownership-404-first;
         *     malformed/non-object body is a 400; missing/non-string ``field``,
         *     non-boolean ``known``, and a non-string ``base_revision`` are 422.
         */
        post: operations["knowledge_toggle_api_campaigns__campaign_id__entities__entity_id__knowledge_toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Edge
         * @description Create a new typed, directed edge in one atomic commit (AR3).
         *
         *     Thin route: type/vocabulary, self-loop, duplicate-relationship, and
         *     counter checks are the store's. The no-orphan rule is entity-create-
         *     only (spec-2.5), so a new edge between committed entities is always
         *     legal and never orphans anyone. The store assigns the edge's ULID
         *     (creation is id=None — explicit ids never create).
         */
        post: operations["create_edge_api_campaigns__campaign_id__edges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/edges/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Campaign Edge
         * @description Delete one edge in one atomic commit (FR9).
         *
         *     No cascade/confirm gate — deleting a single edge is always
         *     dangling-safe (never orphans an entity; the store's no-orphan rule is
         *     entity-create-only). Unknown/foreign edge id is the indistinguishable
         *     404. ``base_revision`` is query-param opt-in optimistic concurrency
         *     (omitted targets the current head — ``delete_edge`` implements that
         *     None-means-head semantics internally, like ``delete_entity``).
         */
        delete: operations["delete_campaign_edge_api_campaigns__campaign_id__edges__edge_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Edge
         * @description Update one edge's counter in one atomic commit (counter-only, AD-2).
         *
         *     src/dst/type are immutable; re-targeting is forbidden, so the PATCH
         *     body carries only the new counter. Unknown/foreign edge id is the
         *     indistinguishable 404; a stale ``base_revision`` is a 409
         *     (StaleRevisionError).
         */
        patch: operations["update_edge_api_campaigns__campaign_id__edges__edge_id__patch"];
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export World
         * @description The complete latest-revision world state as JSON, Obsidian
         *     Markdown, or a self-contained styled HTML document.
         */
        get: operations["export_world_api_campaigns__campaign_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Entity
         * @description One committed entity — edges touching it and the revision head —
         *     as JSON, Markdown, a print-ready HTML sheet, the Owlbear/Forge
         *     transfer payload, the Fantasy Grounds Unity 2024-record XML
         *     (spec-5-3), or the MapTool 1.18.6 ``.rptok`` token ZIP (spec-5-4).
         *     The entity-level projection is the engine Epic 5's VTT adapters
         *     consume (spec-5.1, spec-5-2, spec-5.3).
         */
        get: operations["export_entity_api_campaigns__campaign_id__entities__entity_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaign Candidates
         * @description The campaign's staged proposed candidates, oldest first (AR7).
         *
         *     Owner-only: unauthenticated is a 401; a foreign or unknown campaign
         *     is the single indistinguishable 404. Cursor-paginated per the list
         *     conventions; a fabricated cursor is a 422 (epic-1 retro item 2).
         *     ``status`` filters the closed lifecycle set and defaults to
         *     ``proposed`` — settled rows must not regress the accept-screen read.
         */
        get: operations["list_campaign_candidates_api_campaigns__campaign_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Campaign Candidate
         * @description Commit the candidate's subgraph as one atomic transaction and
         *     settle the row ``accepted`` (spec-3.2, FR11/AD-15).
         *
         *     Owner-first, mirroring ``delete_entity``: a foreign or unknown
         *     campaign is the 404 before anything else is touched. Thin route:
         *     every decision (fresh-ULID entity, staged edges, base revision,
         *     one-transaction atomicity, dead-endpoint rejection) is the store's.
         *     An optional ``{"payload": {...}}`` body (spec-3.3, relaxed by
         *     spec-3.4) carries the DM's edited sections and the DM's own edge
         *     set; the store validates the override against the required AR24
         *     section shape and validates every edge against committed world
         *     state (invalid edge: 422, row stays ``proposed``). A body that is
         *     present WITHOUT a payload (``{}`` or ``{"payload": null}``) is a
         *     422 — only the OMITTED body is the unedited accept, unless it is the
         *     spec-3.6 confirm flag alone (``{"confirm_overwrite": true}`` — the
         *     three-way accept-conflict escape must not force resending the
         *     payload).
         */
        post: operations["accept_campaign_candidate_api_campaigns__campaign_id__candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Campaign Candidate
         * @description Settle the candidate ``rejected`` — the world is untouched (AR7).
         *
         *     Owner-first like the accept route; the store flips the status in one
         *     transaction with no revision, no event, and no world read.
         */
        post: operations["reject_campaign_candidate_api_campaigns__campaign_id__candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Characters
         * @description Submit one or more fully-authored character sheets (202 + job_id).
         *
         *     The body is ``{"campaign_id": <ulid>, "characters": [<sheet>, ...]}``
         *     validated against the canonical JSON Schema (``store.direct``) —
         *     completeness, stat-block structure incl. the dice pattern, well-formed
         *     declared relations, closed key sets, and the ``target_name`` ban
         *     (path 2 has no mandate access). A violation is a 422 whose
         *     ``details.violations`` carry the exact schema paths; zero job rows are
         *     written on any failure. The enqueued job's ``max_llm_calls`` is 0 —
         *     the zero-LLM property is structural.
         */
        post: operations["create_characters_api_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaign Media
         * @description The campaign's media manifest (FOREIGN_CAMPAIGN: owner-only, the
         *     single indistinguishable 404).
         */
        get: operations["list_campaign_media_api_campaigns__campaign_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/reveal-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reveal Prompt Preview
         * @description Preview the canonical automatic prompt without enqueuing a job.
         */
        get: operations["reveal_prompt_preview_api_campaigns__campaign_id__entities__entity_id__reveal_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Media
         * @description Delete ONE manifest row (spec-4.3) — the DM's portrait delete.
         *
         *     ``media_id`` is the manifest ROW id (the media-list projection's
         *     ``id``), never the filename: the row lookup is store-side and scoped
         *     to this campaign AND entity, so a foreign campaign, an unknown id,
         *     and an id belonging to another entity are all the same 404 (AD-9, no
         *     oracle). Ownership is checked FIRST — a foreign/unknown campaign is
         *     the campaign 404.
         *
         *     Media rows are NOT world graph: no event, no revision, and undo
         *     never restores them — the deletion is not undoable and regeneration
         *     is the recovery (``store/media.py``). The FILE is reclaimed after the
         *     rows committed (AD-10 rows-first ordering, spec-4.3): a missing file
         *     is still a 204, never an error.
         */
        delete: operations["delete_media_api_campaigns__campaign_id__entities__entity_id__media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/entities/{entity_id}/portrait-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portrait Url
         * @description Mint the Forge portrait URL: owner-only, absolute, expiring.
         *     Unknown/foreign campaign is the campaign 404; an unknown entity or
         *     one with no available portrait is the entity 404 (same envelope).
         *     An unset secret is the generic 500 after one error log line — fail
         *     closed, never mint unsigned. Read-only (AD-1/AD-11): no revision,
         *     no event, no store write.
         */
        get: operations["portrait_url_api_campaigns__campaign_id__entities__entity_id__portrait_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaigns/{campaign_id}/media/{entity_id}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description One portrait file — ownership + manifest row + disk checks, all 404.
         *     The row lookup is store-side (AD-9) and the disk check is the
         *     ROW_WITHOUT_FILE row: a manifest row whose file was removed is the
         *     same 404, never a server error. The filename is a manifest row's
         *     runner-minted ``<ulid>.png``; the row lookup is the traversal guard
         *     (a non-row name can never reach the filesystem), and separators are
         *     rejected outright.
         *
         *     With ``exp``/``sig`` (spec-5.2) a valid signature bypasses the
         *     session entirely — the portrait URL is pasted into Forge, which
         *     fetches with no cookie. EVERY signed-path failure (absent secret,
         *     missing/expired/tampered params, unknown row, missing file) is the
         *     campaign-missing 404: the signature, the row, and the disk check
         *     are indistinguishable (no oracle). Without the params the cookie
         *     path is unchanged, including its 401.
         */
        get: operations["get_file_api_campaigns__campaign_id__media__entity_id___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptBody
         * @description Optional accept body (spec-3.3, relaxed by spec-3.4, extended by
         *     spec-3.6): the accept screen's edit-before-accept override.
         *     ``payload`` is the full candidate record with the DM's section edits
         *     AND the DM's own edge set (added/edited/deleted staged edges); the
         *     store validates every override edge against committed world state —
         *     an invalid edge is a 422 and the row stays ``proposed``. An omitted
         *     body is the unedited accept (identical to the 3.2 behavior).
         *     ``confirm_overwrite`` (spec-3.6 ACCEPT_ANYWAY): the DM's explicit
         *     confirmation that a regenerate-entity accept may overwrite a hand
         *     edit that landed on the target since staging — a body carrying ONLY
         *     this flag is legal (the three-way escape must not force resending
         *     the payload); the flag alone is NEVER enough for a client to skip a
         *     human confirmation step.
         */
        AcceptBody: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /**
             * Confirm Overwrite
             * @default false
             */
            confirm_overwrite: boolean;
        };
        /** AccountResponse */
        AccountResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** ArchetypeExport */
        ArchetypeExport: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Default Dial */
            default_dial: string;
        };
        /** CampaignCreate */
        CampaignCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Theme */
            theme: string;
            /**
             * Custom Lore
             * @default
             */
            custom_lore: string;
        };
        /** CampaignListResponse */
        CampaignListResponse: {
            /** Campaigns */
            campaigns: components["schemas"]["CampaignResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CampaignMeta */
        CampaignMeta: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Theme */
            theme: string;
            /** Description */
            description: string;
            /** Custom Lore */
            custom_lore: string;
            /** Is Generic */
            is_generic: boolean;
            /** Created At */
            created_at: string;
        };
        /** CampaignResponse */
        CampaignResponse: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Theme */
            theme: string;
            /** Custom Lore */
            custom_lore: string;
            /** Is Generic */
            is_generic: boolean;
            /** Created At */
            created_at: string;
        };
        /** CampaignUpdate */
        CampaignUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Theme */
            theme?: string | null;
            /** Custom Lore */
            custom_lore?: string | null;
        };
        /**
         * CandidateListResponse
         * @description Cursor-paginated, campaign-scoped candidate list.
         */
        CandidateListResponse: {
            /** Candidates */
            candidates: components["schemas"]["CandidateResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * CandidateResponse
         * @description One staged proposed-candidate row.
         */
        CandidateResponse: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Accepted Entity Id */
            accepted_entity_id?: string | null;
            /** Accept Revision Id */
            accept_revision_id?: string | null;
            /** Regenerates Entity Id */
            regenerates_entity_id?: string | null;
        };
        /** EdgeExport */
        EdgeExport: {
            /** Id */
            id: string;
            /** Src */
            src: string;
            /** Dst */
            dst: string;
            /** Type */
            type: string;
            /** Counter */
            counter: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * EdgeResponse
         * @description The wire shape of one committed edge (mirrors EdgeExport).
         *
         *     ``reason`` is the AD-32 saved why; pre-v3 rows read NULL.
         */
        EdgeResponse: {
            /** Id */
            id: string;
            /** Src */
            src: string;
            /** Dst */
            dst: string;
            /** Type */
            type: string;
            /** Counter */
            counter: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * EdgeTypeRule
         * @description One closed-vocabulary cell: allowed kinds and the AD-23 counter
         *     semantic (``None`` = any kind).
         */
        EdgeTypeRule: {
            /** Src */
            src: string[] | null;
            /** Dst */
            dst: string[] | null;
            /** Counter Semantic */
            counter_semantic: string;
            /** Counter Bounds */
            counter_bounds: number[] | null;
        };
        /** EntityExport */
        EntityExport: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Text */
            text: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Media */
            media: components["schemas"]["MediaRefExport"][];
        };
        /**
         * EntityExportDetail
         * @description The single-entity JSON projection (spec-5.1): the entity, every
         *     edge touching it (rowid order — the same ordering the world document
         *     renders), and the revision head the snapshot was taken at.
         */
        EntityExportDetail: {
            entity: components["schemas"]["EntityExport"];
            /** Edges */
            edges: components["schemas"]["EdgeExport"][];
            revision: components["schemas"]["RevisionMeta"] | null;
        };
        /**
         * EventSummary
         * @description One display-ready event summary (AD-35): the Tonight feed renders
         *     these verbatim. ``actor`` is the sole DM in beta (AD-9: one invited
         *     user per campaign — no actor column exists to fabricate one).
         */
        EventSummary: {
            /** Revision Id */
            revision_id: string;
            /** Created At */
            created_at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target Names */
            target_names: string[];
            /** Kind */
            kind: string;
            /** Details */
            details?: string[];
        };
        /** GenericWorldCreate */
        GenericWorldCreate: {
            /** Theme */
            theme: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreate
         * @description POST /api/jobs body — the job-submission wire contract.
         */
        JobCreate: {
            /** Campaign Id */
            campaign_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "image" | "video" | "video_prompt" | "build_in" | "generate" | "regenerate" | "add_character";
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Job Id */
            job_id?: string | null;
            /** Max Llm Calls */
            max_llm_calls?: number | null;
            /** Max Media Calls */
            max_media_calls?: number | null;
        };
        /**
         * JobListResponse
         * @description Cursor-paginated, campaign-scoped job list.
         */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * JobResponse
         * @description A job row plus its per-campaign queue position.
         */
        JobResponse: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** State */
            state: string;
            /** Progress */
            progress: number;
            /** Max Llm Calls */
            max_llm_calls: number;
            /** Max Media Calls */
            max_media_calls: number;
            /** Error */
            error: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Queue Position */
            queue_position: number | null;
        };
        /**
         * KindsResponse
         * @description The code-wins registry (AD-34): the endpoint owns no vocabulary —
         *     everything renders the store's constants, cacheable within the
         *     version token, re-fetched per walk mount. Commit-time live
         *     validation against the same matrix is the backstop.
         */
        KindsResponse: {
            /** Version */
            version: string;
            /** Edge Types */
            edge_types: string[];
            /** Kind Rules */
            kind_rules: {
                [key: string]: components["schemas"]["EdgeTypeRule"];
            };
            /** Dial Levels */
            dial_levels: string[];
            /** Archetypes */
            archetypes: components["schemas"]["ArchetypeExport"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MediaListResponse
         * @description The campaign's media manifest, rowid (insertion) order.
         */
        MediaListResponse: {
            /** Media */
            media: components["schemas"]["MediaResponse"][];
        };
        /**
         * MediaRefExport
         * @description One manifest row riding an entity's export (spec-4.3, FR14):
         *     ``available`` is the file's on-disk presence — a broken reference is
         *     flagged, never dropped or hidden.
         */
        MediaRefExport: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Filename */
            filename: string;
            /** Available */
            available: boolean;
        };
        /**
         * MediaResponse
         * @description One media manifest row (AD-10) — the entity card's portrait index.
         */
        MediaResponse: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Entity Id */
            entity_id: string;
            /** Filename */
            filename: string;
            /** Kind */
            kind: string;
            /** Created At */
            created_at: string;
        };
        /** MoveCharacterIn */
        MoveCharacterIn: {
            /** Source Campaign Id */
            source_campaign_id: string;
            /** Entity Id */
            entity_id: string;
        };
        /**
         * PortraitUrlResponse
         * @description A signed, expiring portrait URL for Forge's per-unit portrait
         *     override (spec-5.2) — absolute, fetchable with no session.
         */
        PortraitUrlResponse: {
            /** Url */
            url: string;
            /** Expires At */
            expires_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * RevealPromptResponse
         * @description The exact appearance-based prompt available for a reveal render.
         */
        RevealPromptResponse: {
            /** Prompt */
            prompt: string;
        };
        /** RevisionMeta */
        RevisionMeta: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
        };
        /**
         * RevisionSummary
         * @description One revision's display-ready projection: meta + its event summaries.
         */
        RevisionSummary: {
            /** Revision Id */
            revision_id: string;
            /** Created At */
            created_at: string;
            /** Events */
            events: components["schemas"]["EventSummary"][];
        };
        /**
         * RevisionsResponse
         * @description Bounded, newest-first revision history (AD-35: default 20, max
         *     100). Meta + display-ready event summaries only — never a write
         *     surface, never world state.
         */
        RevisionsResponse: {
            /** Default */
            default: number;
            /** Max */
            max: number;
            /** Revisions */
            revisions: components["schemas"]["RevisionSummary"][];
        };
        /**
         * RunStateResponse
         * @description Tonight's Tier-2 run-state (AD-28): the chip/cast read — dumb
         *     joins, never a write surface. ``session`` maps entity id to the
         *     full session-image (defeated flag, hp delta, allegiance, thread,
         *     item counters); ``knowledge`` maps entity id to its per-secret
         *     toggles over the closed secret/rumor/party_hook set. A row that
         *     does not exist is absent — a fresh world reads two empty maps,
         *     never an error, never a fabricated default.
         */
        RunStateResponse: {
            /** Session */
            session: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Knowledge */
            knowledge: {
                [key: string]: {
                    [key: string]: boolean;
                };
            };
        };
        /**
         * ThemesResponse
         * @description The AR27 theme seed list (config ``campaigns.themes``) — the
         *     create/update forms choose from this; free text is a 422 (dogfood
         *     fix 2026-09-09: the store always validated, the form never showed).
         */
        ThemesResponse: {
            /** Themes */
            themes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorldExport */
        WorldExport: {
            campaign: components["schemas"]["CampaignMeta"];
            revision: components["schemas"]["RevisionMeta"] | null;
            /** Entities */
            entities: components["schemas"]["EntityExport"][];
            /** Edges */
            edges: components["schemas"]["EdgeExport"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_own_api_campaigns_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_themes_api_campaigns_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kinds_api_campaigns_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KindsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_api_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_campaigns__campaign_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_api_campaigns__campaign_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_history_api_campaigns__campaign_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_state_api_campaigns__campaign_id__run_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_generic_api_campaigns_generic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenericWorldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_character_api_campaigns__campaign_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCharacterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_campaign_jobs_api_jobs_get: {
        parameters: {
            query: {
                campaign_id: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_route_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_api_campaigns__campaign_id__entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_campaigns__campaign_id__entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_verb_api_campaigns__campaign_id__entities__entity_id__session_verb_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_toggle_api_campaigns__campaign_id__entities__entity_id__knowledge_toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_edge_api_campaigns__campaign_id__edges_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_edge_api_campaigns__campaign_id__edges__edge_id__delete: {
        parameters: {
            query?: {
                base_revision?: string | null;
            };
            header?: never;
            path: {
                campaign_id: string;
                edge_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_edge_api_campaigns__campaign_id__edges__edge_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                edge_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_world_api_campaigns__campaign_id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "markdown" | "html";
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The latest-revision world export: WorldExport JSON by default, or an Obsidian-markdown / standalone-HTML attachment via ?format=. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldExport"];
                    "text/markdown": string;
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_entity_api_campaigns__campaign_id__entities__entity_id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "markdown" | "html" | "owlbear" | "fg" | "maptool";
            };
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The entity export: EntityExportDetail JSON by default, or a format-specific attachment (markdown / html / owlbear JSON / fg XML / maptool .rptok zip) via ?format=. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityExportDetail"];
                    "text/markdown": string;
                    "text/html": string;
                    "text/xml": string;
                    "application/zip": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaign_candidates_api_campaigns__campaign_id__candidates_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                status?: string;
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_campaign_candidate_api_campaigns__campaign_id__candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                candidate_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AcceptBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_campaign_candidate_api_campaigns__campaign_id__candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                candidate_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_characters_api_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaign_media_api_campaigns__campaign_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_prompt_preview_api_campaigns__campaign_id__entities__entity_id__reveal_prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_api_campaigns__campaign_id__entities__entity_id__media__media_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
                media_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portrait_url_api_campaigns__campaign_id__entities__entity_id__portrait_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortraitUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_campaigns__campaign_id__media__entity_id___filename__get: {
        parameters: {
            query?: {
                exp?: string | null;
                sig?: string | null;
            };
            header?: never;
            path: {
                campaign_id: string;
                entity_id: string;
                filename: string;
            };
            cookie?: {
                mythoscircle_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The media file bytes inline (video/mp4 for video rows, image/png for portraits). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "video/mp4": string;
                    "image/png": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
