/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Register
     * @description Create an account; the password is argon2id-hashed, never stored.
     */
    post: operations['register_api_auth_register_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Verify credentials, set the session cookie, return the account.
     *
     *     Every failure — unknown email, wrong password, rate-limit lockout —
     *     is the same generic 401 (AR29, no user enumeration). The limiter key
     *     uses the NORMALIZED email (the same form the store compares), so
     *     case-rotating ``DM@example.com`` / ``dm@example.com`` cannot mint
     *     fresh attempt budgets (review round 1). Only failures consume quota —
     *     five legit logins never lock a user out.
     */
    post: operations['login_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Revoke the session immediately and clear the cookie; idempotent.
     */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Me
     * @description Return the authenticated account.
     */
    get: operations['me_api_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/campaigns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Own
     * @description The caller's campaigns, oldest first, cursor-paginated.
     */
    get: operations['list_own_api_campaigns_get']
    put?: never
    /**
     * Create
     * @description Create a private world owned by the caller (AR27, AD-9).
     */
    post: operations['create_api_campaigns_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/campaigns/{campaign_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get One
     * @description One owned campaign — foreign/unknown is a single 404 (no oracle).
     */
    get: operations['get_one_api_campaigns__campaign_id__get']
    put?: never
    post?: never
    /**
     * Delete
     * @description AR20 total hard delete — requires an explicit confirmation body.
     *
     *     Frozen contract (spec-1.6): ``DELETE`` with a JSON body
     *     ``{"confirm": true}``; missing/false confirm -> 400, nothing deleted.
     *     The body is echoed via ``request`` (FastAPI cannot bind a Pydantic
     *     body to DELETE directly) and malformed JSON is a 400. Ownership is
     *     checked FIRST: a foreign id is always 404, even without the confirm
     *     body (matrix row DELETE_FOREIGN).
     */
    delete: operations['delete_api_campaigns__campaign_id__delete']
    options?: never
    head?: never
    /**
     * Update
     * @description Update seed fields of an owned campaign (PATCH semantics).
     */
    patch: operations['update_api_campaigns__campaign_id__patch']
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return the service health status.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Campaign Jobs
     * @description Campaign-scoped FIFO list, oldest first, cursor-paginated (AD-9).
     */
    get: operations['list_campaign_jobs_api_jobs_get']
    put?: never
    /**
     * Create Job
     * @description Enqueue a job at the FIFO tail; idempotent by job_id (AD-3, AR28).
     */
    post: operations['create_job_api_jobs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job
     * @description One job plus its current queue position (STATUS_POSITION).
     */
    get: operations['get_job_api_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/jobs/{job_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Job Route
     * @description Cancel a queued or running job; frees the queue slot (AR28).
     */
    post: operations['cancel_job_route_api_jobs__job_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AccountResponse */
    AccountResponse: {
      /** Id */
      id: string
      /** Email */
      email: string
    }
    /** CampaignCreate */
    CampaignCreate: {
      /** Title */
      title: string
      /**
       * Description
       * @default
       */
      description: string
      /** Theme */
      theme: string
      /**
       * Custom Lore
       * @default
       */
      custom_lore: string
    }
    /** CampaignListResponse */
    CampaignListResponse: {
      /** Campaigns */
      campaigns: components['schemas']['CampaignResponse'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /** CampaignResponse */
    CampaignResponse: {
      /** Id */
      id: string
      /** Owner Id */
      owner_id: string
      /** Title */
      title: string
      /** Description */
      description: string
      /** Theme */
      theme: string
      /** Custom Lore */
      custom_lore: string
      /** Created At */
      created_at: string
    }
    /** CampaignUpdate */
    CampaignUpdate: {
      /** Title */
      title?: string | null
      /** Description */
      description?: string | null
      /** Theme */
      theme?: string | null
      /** Custom Lore */
      custom_lore?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * JobCreate
     * @description POST /api/jobs body — the job-submission wire contract.
     */
    JobCreate: {
      /** Campaign Id */
      campaign_id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'text' | 'image' | 'video' | 'build_in'
      /** Payload */
      payload: {
        [key: string]: unknown
      }
      /** Job Id */
      job_id?: string | null
      /** Max Llm Calls */
      max_llm_calls?: number | null
      /** Max Media Calls */
      max_media_calls?: number | null
    }
    /**
     * JobListResponse
     * @description Cursor-paginated, campaign-scoped job list.
     */
    JobListResponse: {
      /** Jobs */
      jobs: components['schemas']['JobResponse'][]
      /** Next Cursor */
      next_cursor: string | null
    }
    /**
     * JobResponse
     * @description A job row plus its per-campaign queue position.
     */
    JobResponse: {
      /** Id */
      id: string
      /** Campaign Id */
      campaign_id: string
      /** Kind */
      kind: string
      /** Payload */
      payload: {
        [key: string]: unknown
      }
      /** State */
      state: string
      /** Progress */
      progress: number
      /** Max Llm Calls */
      max_llm_calls: number
      /** Max Media Calls */
      max_media_calls: number
      /** Error */
      error: string | null
      /** Result */
      result: {
        [key: string]: unknown
      } | null
      /** Created At */
      created_at: string
      /** Started At */
      started_at: string | null
      /** Finished At */
      finished_at: string | null
      /** Queue Position */
      queue_position: number | null
    }
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
    }
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  register_api_auth_register_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_own_api_campaigns_get: {
    parameters: {
      query?: {
        cursor?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_api_campaigns_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_one_api_campaigns__campaign_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        campaign_id: string
      }
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_api_campaigns__campaign_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        campaign_id: string
      }
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_api_campaigns__campaign_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        campaign_id: string
      }
      cookie?: {
        mythoscircle_session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CampaignUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CampaignResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  list_campaign_jobs_api_jobs_get: {
    parameters: {
      query: {
        campaign_id: string
        cursor?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_job_api_jobs_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JobCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_job_api_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_job_route_api_jobs__job_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
