#!/usr/bin/env bash
# One-command deploy: install Caddy, the systemd unit, config, the env
# file, the backup cron, the backend, and the frontend build (spec-1.7).
#
# Idempotent. Everything is installable under a stage root for testing
# without root:
#   DEPLOY_STAGE=/tmp/mycircle-stage ./deploy.sh
# Privileged steps use ${SUDO:-sudo}; SKIP_SERVICE=1 skips systemctl.
set -euo pipefail

STAGE="${DEPLOY_STAGE:-}"
SUDO_CMD="${SUDO:-sudo}"

# Stage-prefixed install: real / when no stage, $STAGE when set.
stage() { if [ -n "$STAGE" ]; then printf '%s/%s' "$STAGE" "$1"; else printf '%s' "$1"; fi; }

# Install helper: create the parent dir then install the file.
install_with_parents() {
	local src="$1" dest="$2"
	mkdir -p "$(dirname "$dest")"
	install -m 0644 "$src" "$dest"
}

echo "== mythosCircle deploy (stage: ${STAGE:-/}) =="

# 1. Config + env file.
CONF_DEST="$(stage /etc/mythoscircle)"
mkdir -p "$CONF_DEST"
install -m 0644 deploy/config.toml "$CONF_DEST/config.toml"

# The env file carries the non-secret config values (spec-1.7 promise);
# secrets go below the marker after deploy (AD-22: never in config/repo).
ENV_DEST="$CONF_DEST/mythoscircle.env"
GENERATED_ENV="# Generated by deploy.sh — add SECRETS below this line (AD-22)."
printf '%s\n' "$GENERATED_ENV" > "$ENV_DEST"
# Non-secret values from config.toml, so systemd's EnvironmentFile actually
# carries the operator's runtime config (env > config > default).
if command -v python3 >/dev/null 2>&1; then
	python3 - "$GENERATED_ENV" <<'PYEOF' >> "$ENV_DEST"
import sys
import tomllib
from pathlib import Path
path = Path("deploy/config.toml")
try:
    cfg = tomllib.loads(path.read_text())
except FileNotFoundError:
    sys.exit(0)
world, queue, llm, campaigns = cfg.get("world", {}), cfg.get("queue", {}), cfg.get("llm", {}), cfg.get("campaigns", {})
entries = [
    ("MYTHOSCIRCLE_MAX_PENDING_PER_CAMPAIGN", queue.get("max_in_flight_per_campaign")),
    ("MYTHOSCIRCLE_LLM_ENDPOINT", llm.get("endpoint")),
    ("MYTHOSCIRCLE_LLM_MODEL", llm.get("model")),
    ("MYTHOSCIRCLE_LLM_TIMEOUT", llm.get("timeout")),
    ("MYTHOSCIRCLE_DB", world.get("sqlite_path")),
    ("MYTHOSCIRCLE_LOG_FILE", world.get("log_file")),
]
for name, value in entries:
    if value is not None:
        print(f"{name}={value}")
PYEOF
fi
chmod 600 "$ENV_DEST"

# 2. Backend provision: source + venv + deps (the unit's ExecStart target).
BACKEND_DEST="$(stage /opt/mythoscircle/backend)"
mkdir -p "$BACKEND_DEST"
if [ -d backend/app ]; then
	cp -r backend/app "$BACKEND_DEST/app"
	cp -r backend/pyproject.toml backend/uv.lock "$BACKEND_DEST/"
	# Create a fresh venv with uvicorn + deps (uv when available, else pip).
	if command -v uv >/dev/null 2>&1; then
		( cd "$BACKEND_DEST" && uv venv .venv && uv pip install --python .venv/bin/python -e . )
	else
		( cd "$BACKEND_DEST" && python3 -m venv .venv && .venv/bin/pip install uvicorn fastapi "sqlalchemy>=2.0,<3" "pydantic>=2.13,<3" "python-ulid>=4,<5" "httpx>=0.28,<1" "argon2-cffi>=25,<26" "email-validator>=2,<3" "websockets>=15,<16" )
	fi
fi

# 3. Deploy scripts (the cron references /opt/mythoscircle/deploy/backup.sh).
DEPLOY_DEST="$(stage /opt/mythoscircle/deploy)"
mkdir -p "$DEPLOY_DEST"
install_with_parents deploy/backup.sh "$DEPLOY_DEST/backup.sh"
install_with_parents deploy/restore.sh "$DEPLOY_DEST/restore.sh"
# Docker-stack wrapper ships in the same tree (the laptop compose host
# scp's it like backup.docker.cron; keeping it provisioned here pins it
# to CI's stage-tree test and gives one canonical source).
install_with_parents deploy/restore.docker.sh "$DEPLOY_DEST/restore.docker.sh"

# 4. Systemd unit.
install_with_parents deploy/mythoscircle.service "$(stage /etc/systemd/system/mythoscircle.service)"

# 5. Caddy site config.
install_with_parents deploy/Caddyfile "$(stage /etc/caddy/Caddyfile)"

# 6. Backup cron (registered per AR1; snapshot+restore proof lands in Epic 6).
install_with_parents deploy/backup.cron "$(stage /etc/cron.d/mythoscircle-backup)"

# 7. Frontend build installed to the web root.
WEB_ROOT="$(stage /var/www/mythoscircle)"
echo "== building frontend =="
FRONTEND_BUILD="$(mktemp -d)"
( cd frontend && npm ci --silent && npm run build --silent -- --outDir "$FRONTEND_BUILD" )
mkdir -p "$WEB_ROOT"
rm -rf "${WEB_ROOT:?}/dist"
mv "$FRONTEND_BUILD" "$WEB_ROOT/dist"

# 8. Runtime dirs + user (only on the real root; stage just makes dirs).
mkdir -p "$(stage /var/lib/mythoscircle/media)" "$(stage /var/log/mythoscircle)" "$(stage /opt/mythoscircle)"
if [ -z "$STAGE" ]; then
	"$SUDO_CMD" useradd --system --home /opt/mythoscircle --shell /usr/sbin/nologin mythoscircle 2>/dev/null || true
	"$SUDO_CMD" chown -R mythoscircle:mythoscircle /opt/mythoscircle /var/lib/mythoscircle /var/log/mythoscircle
fi

# 9. Services (skippable for tests). Fail loudly: a dead site must not
# report "deploy complete" (spec-1.7 Never: no silent failures).
if [ "${SKIP_SERVICE:-0}" != "1" ] && [ -z "$STAGE" ]; then
	echo "== enabling services =="
	"$SUDO_CMD" systemctl daemon-reload
	"$SUDO_CMD" systemctl enable --now caddy || { echo "caddy enable failed" >&2; exit 1; }
	"$SUDO_CMD" systemctl enable --now mythoscircle.service || { echo "mythoscircle enable failed" >&2; exit 1; }
fi

echo "== deploy complete =="
echo "   config:      $CONF_DEST/config.toml"
echo "   env (secrets): $ENV_DEST"
echo "   backend:     $BACKEND_DEST"
echo "   deploy scripts: $DEPLOY_DEST"
echo "   frontend:    $WEB_ROOT/dist"
if [ -n "$STAGE" ]; then
	echo "   (staged — run without DEPLOY_STAGE on the operator host)"
fi