"""World store — the sole writer of world state (AD-1).

Every mutation of the world graph flows through a store commit: atomic
subgraph transactions, one revision per commit, per-transaction undo.
Nothing else in the codebase writes world state.

The persistent generation queue (AD-3) lives in the same database: job
rows and transitions never touch the event log or revisions (AD-13).

Public API:
    init_db / init_app_db / session_scope   -- engine & transactions (db)
    create_campaign / commit_subgraph       -- the commit path (commit)
    undo                                    -- compensating commit (undo)
    campaign_seed / latest_revision / revision_chain / revision_events /
        world_entities / world_edges / world_state (read)
    enqueue_job / claim_next_job / complete_job / fail_job /
        report_progress / cancel_job / job_status / list_jobs /
        set_change_listener                 -- generation queue (jobs)
"""

from app.store.auth import (
    EmailTakenError,
    create_session,
    get_session_account,
    register_account,
    revoke_session,
    verify_login,
)
from app.store.campaigns import (
    CampaignInputError,
    InvalidThemeError,
    create_campaign,
    delete_campaign,
    get_campaign,
    list_campaigns,
    normalize_theme,
    update_campaign,
)
from app.store.commit import (
    DEFAULT_EDGE_COUNTER_SEMANTIC,
    EDGE_COUNTER_SEMANTICS,
    EDGE_TYPES,
    CorruptEventError,
    CrossCampaignConflictError,
    DanglingEdgeError,
    DuplicateEdgeError,
    DuplicateEntityError,
    EdgeRetargetError,
    EmptySubgraphError,
    InvalidEdgeCounterError,
    InvalidEdgeTypeError,
    InvalidUlidError,
    LiveEdgesError,
    OrphanEntityError,
    SelfLoopEdgeError,
    StaleRevisionError,
    StoreError,
    UnknownCampaignError,
    UnknownEntityError,
    commit_subgraph,
    delete_entity,
    edge_counter_semantic,
)
from app.store.db import (
    DB_ENV_VAR,
    DEFAULT_DB_URL,
    app_db_url,
    get_engine,
    init_app_db,
    init_db,
    session_scope,
)
from app.store.jobs import (
    DEFAULT_LIST_LIMIT,
    EVENT_JOB_CANCELLED,
    EVENT_JOB_DONE,
    EVENT_JOB_FAILED,
    EVENT_JOB_PROGRESS,
    EVENT_QUEUE_CHANGED,
    JOB_KINDS,
    JOB_STATES,
    PENDING_STATES,
    TERMINAL_STATES,
    DuplicateJobError,
    InvalidJobInputError,
    JobNotFoundError,
    JobStateConflictError,
    QueueFullError,
    cancel_job,
    claim_next_job,
    complete_job,
    enqueue_job,
    fail_job,
    job_status,
    list_jobs,
    recover_stale_running,
    report_progress,
    set_change_listener,
)
from app.store.models import (
    Account,
    Base,
    Campaign,
    Edge,
    EdgeInput,
    Entity,
    EntityInput,
    Event,
    Job,
    Media,
    Revision,
    Session,
)
from app.store.read import (
    campaign_seed,
    entity_live_edges,
    latest_revision,
    revision_chain,
    revision_events,
    world_edges,
    world_entities,
    world_state,
)
from app.store.undo import undo

__all__ = [
    "Account",
    "Base",
    "Campaign",
    "CampaignInputError",
    "CorruptEventError",
    "CrossCampaignConflictError",
    "DB_ENV_VAR",
    "DEFAULT_DB_URL",
    "DEFAULT_EDGE_COUNTER_SEMANTIC",
    "DEFAULT_LIST_LIMIT",
    "DanglingEdgeError",
    "DuplicateEdgeError",
    "DuplicateEntityError",
    "DuplicateJobError",
    "EDGE_COUNTER_SEMANTICS",
    "EDGE_TYPES",
    "EVENT_JOB_CANCELLED",
    "EVENT_JOB_DONE",
    "EVENT_JOB_FAILED",
    "EVENT_JOB_PROGRESS",
    "EVENT_QUEUE_CHANGED",
    "Edge",
    "EdgeInput",
    "EdgeRetargetError",
    "EmailTakenError",
    "EmptySubgraphError",
    "Entity",
    "EntityInput",
    "Event",
    "InvalidEdgeCounterError",
    "InvalidEdgeTypeError",
    "InvalidJobInputError",
    "InvalidThemeError",
    "InvalidUlidError",
    "JOB_KINDS",
    "JOB_STATES",
    "Job",
    "JobNotFoundError",
    "JobStateConflictError",
    "LiveEdgesError",
    "OrphanEntityError",
    "SelfLoopEdgeError",
    "Media",
    "PENDING_STATES",
    "QueueFullError",
    "Revision",
    "Session",
    "StaleRevisionError",
    "StoreError",
    "TERMINAL_STATES",
    "UnknownCampaignError",
    "UnknownEntityError",
    "app_db_url",
    "campaign_seed",
    "cancel_job",
    "claim_next_job",
    "commit_subgraph",
    "complete_job",
    "create_campaign",
    "create_session",
    "delete_campaign",
    "delete_entity",
    "edge_counter_semantic",
    "entity_live_edges",
    "enqueue_job",
    "fail_job",
    "get_campaign",
    "get_engine",
    "get_session_account",
    "init_app_db",
    "init_db",
    "job_status",
    "latest_revision",
    "list_campaigns",
    "list_jobs",
    "normalize_theme",
    "recover_stale_running",
    "register_account",
    "report_progress",
    "revision_chain",
    "revision_events",
    "revoke_session",
    "session_scope",
    "set_change_listener",
    "undo",
    "update_campaign",
    "verify_login",
    "world_edges",
    "world_entities",
    "world_state",
]
