"""World store — the sole writer of world state (AD-1).

Every mutation of the world graph flows through a store commit: atomic
subgraph transactions, one revision per commit, per-transaction undo.
Nothing else in the codebase writes world state.

The persistent generation queue (AD-3) lives in the same database: job
rows and transitions never touch the event log or revisions (AD-13).

Public API:
    init_db / init_app_db / session_scope   -- engine & transactions (db)
    create_campaign / commit_subgraph       -- the commit path (commit)
    undo                                    -- compensating commit (undo)
    campaign_seed / latest_revision / revision_chain / revision_events /
        world_entities / world_edges / world_state (read)
    enqueue_job / claim_next_job / complete_job / fail_job /
        report_progress / cancel_job / job_status / list_jobs /
        set_change_listener                 -- generation queue (jobs)
    stage_candidates / accept_candidate / reject_candidate /
        list_candidates                     -- proposed candidates (candidates)
    add_media / list_media / get_media_file / delete_one_media
        -- media manifest (media)
"""

from app.store.auth import (
    EmailTakenError,
    create_session,
    get_session_account,
    register_account,
    revoke_session,
    verify_login,
)
from app.store.campaigns import (
    CampaignInputError,
    InvalidThemeError,
    create_campaign,
    delete_campaign,
    get_campaign,
    list_campaigns,
    normalize_theme,
    update_campaign,
)
from app.store.candidates import (
    BOSS_FIELDS,
    BOSS_ROLES,
    IDENTITY_FIELDS,
    LORE_FIELDS,
    PROPOSAL_KIND,
    PROPOSAL_STATUS,
    REGEN_SECTIONS,
    ROLES,
    STATUS_ACCEPTED,
    STATUS_PROPOSED,
    STATUS_REJECTED,
    WORLD_INTEGRATION_FIELDS,
    CandidateNotFoundError,
    CandidateSettledError,
    InvalidCandidateError,
    accept_candidate,
    discard_candidates,
    list_candidates,
    payload_section_violations,
    reject_candidate,
    replace_candidate_payload,
    stage_candidates,
)
from app.store.commit import (
    ARCHETYPES,
    DEFAULT_EDGE_COUNTER_SEMANTIC,
    DIAL_LEVELS,
    EDGE_COUNTER_SEMANTICS,
    EDGE_KIND_RULES,
    EDGE_TYPES,
    KNOWLEDGE_FIELDS,
    NULL_PROSE_REASONS,
    BlankEdgeReasonError,
    CorruptEventError,
    CrossCampaignConflictError,
    DanglingEdgeError,
    DuplicateEdgeError,
    DuplicateEntityError,
    EdgeKindViolationError,
    EdgeRetargetError,
    EmptySubgraphError,
    EntityEditConflictError,
    InvalidEdgeCounterError,
    InvalidEdgeTypeError,
    InvalidEntityRecordError,
    InvalidRunStateError,
    InvalidUlidError,
    LiveEdgesError,
    OrphanEntityError,
    SelfLoopEdgeError,
    StaleRevisionError,
    StoreError,
    UnknownCampaignError,
    UnknownEdgeError,
    UnknownEntityError,
    UnknownRunStateError,
    commit_knowledge_toggle,
    commit_run_state,
    commit_session_verb,
    commit_subgraph,
    delete_edge,
    delete_entity,
    edge_counter_bounds,
    edge_counter_semantic,
    edge_kind_ok,
    edge_reason_ok,
    update_entity,
)
from app.store.db import (
    DB_ENV_VAR,
    DEFAULT_DB_URL,
    app_db_url,
    get_engine,
    init_app_db,
    init_db,
    session_scope,
)
from app.store.jobs import (
    DEFAULT_LIST_LIMIT,
    EVENT_JOB_CANCELLED,
    EVENT_JOB_DONE,
    EVENT_JOB_FAILED,
    EVENT_JOB_PROGRESS,
    EVENT_QUEUE_CHANGED,
    JOB_KINDS,
    JOB_STATES,
    PENDING_STATES,
    TERMINAL_STATES,
    DuplicateJobError,
    InvalidJobInputError,
    JobNotFoundError,
    JobStateConflictError,
    QueueFullError,
    cancel_job,
    claim_next_job,
    complete_job,
    enqueue_job,
    fail_job,
    job_status,
    list_jobs,
    recover_stale_running,
    report_progress,
    set_change_listener,
)
from app.store.media import (
    InvalidMediaError,
    MediaNotFoundError,
    add_media,
    delete_entity_media,
    delete_media_row,
    delete_one_media,
    get_media_file,
    list_media,
    prune_entity_media,
)
from app.store.models import (
    Account,
    Base,
    Campaign,
    Edge,
    EdgeInput,
    Entity,
    EntityInput,
    EntityKnowledgeState,
    EntitySessionState,
    Event,
    Job,
    KnowledgeFlipInput,
    LoginSession,
    Media,
    ProposedCandidate,
    Revision,
    SessionStateInput,
)
from app.store.read import (
    campaign_seed,
    entity_live_edges,
    latest_revision,
    revision_chain,
    revision_events,
    world_edges,
    world_entities,
    world_state,
)
from app.store.undo import undo

__all__ = [
    "Account",
    "Base",
    "BOSS_FIELDS",
    "BOSS_ROLES",
    "Campaign",
    "CampaignInputError",
    "CandidateNotFoundError",
    "CandidateSettledError",
    "CorruptEventError",
    "ARCHETYPES",
    "BlankEdgeReasonError",
    "CrossCampaignConflictError",
    "DB_ENV_VAR",
    "DEFAULT_DB_URL",
    "DEFAULT_EDGE_COUNTER_SEMANTIC",
    "DEFAULT_LIST_LIMIT",
    "DanglingEdgeError",
    "DuplicateEdgeError",
    "DuplicateEntityError",
    "DuplicateJobError",
    "DIAL_LEVELS",
    "EDGE_COUNTER_SEMANTICS",
    "EDGE_KIND_RULES",
    "EDGE_TYPES",
    "EVENT_JOB_CANCELLED",
    "EVENT_JOB_DONE",
    "EVENT_JOB_FAILED",
    "EVENT_JOB_PROGRESS",
    "EVENT_QUEUE_CHANGED",
    "Edge",
    "EdgeInput",
    "EdgeKindViolationError",
    "EdgeRetargetError",
    "EmailTakenError",
    "EmptySubgraphError",
    "Entity",
    "EntityEditConflictError",
    "EntityInput",
    "EntityKnowledgeState",
    "EntitySessionState",
    "Event",
    "IDENTITY_FIELDS",
    "InvalidCandidateError",
    "InvalidEdgeCounterError",
    "InvalidEdgeTypeError",
    "InvalidEntityRecordError",
    "InvalidRunStateError",
    "InvalidJobInputError",
    "InvalidMediaError",
    "InvalidThemeError",
    "InvalidUlidError",
    "JOB_KINDS",
    "JOB_STATES",
    "Job",
    "JobNotFoundError",
    "KnowledgeFlipInput",
    "JobStateConflictError",
    "KNOWLEDGE_FIELDS",
    "LORE_FIELDS",
    "LiveEdgesError",
    "Media",
    "MediaNotFoundError",
    "NULL_PROSE_REASONS",
    "OrphanEntityError",
    "PENDING_STATES",
    "PROPOSAL_KIND",
    "PROPOSAL_STATUS",
    "ProposedCandidate",
    "QueueFullError",
    "REGEN_SECTIONS",
    "ROLES",
    "Revision",
    "SelfLoopEdgeError",
    "LoginSession",
    "SessionStateInput",
    "StaleRevisionError",
    "STATUS_ACCEPTED",
    "STATUS_PROPOSED",
    "STATUS_REJECTED",
    "StoreError",
    "TERMINAL_STATES",
    "WORLD_INTEGRATION_FIELDS",
    "UnknownCampaignError",
    "UnknownEdgeError",
    "UnknownRunStateError",
    "UnknownEntityError",
    "accept_candidate",
    "add_media",
    "app_db_url",
    "campaign_seed",
    "cancel_job",
    "claim_next_job",
    "commit_knowledge_toggle",
    "commit_run_state",
    "commit_session_verb",
    "commit_subgraph",
    "complete_job",
    "create_campaign",
    "create_session",
    "commit_run_state",
    "commit_session_verb",
    "commit_subgraph",
    "complete_job",
    "create_campaign",
    "delete_campaign",
    "delete_entity_media",
    "delete_media_row",
    "delete_one_media",
    "edge_kind_ok",
    "edge_reason_ok",
    "delete_edge",
    "delete_entity",
    "discard_candidates",
    "edge_counter_bounds",
    "edge_counter_semantic",
    "entity_live_edges",
    "enqueue_job",
    "fail_job",
    "get_campaign",
    "get_engine",
    "get_media_file",
    "get_session_account",
    "init_app_db",
    "init_db",
    "job_status",
    "latest_revision",
    "list_campaigns",
    "list_candidates",
    "list_jobs",
    "list_media",
    "normalize_theme",
    "payload_section_violations",
    "prune_entity_media",
    "recover_stale_running",
    "register_account",
    "reject_candidate",
    "replace_candidate_payload",
    "report_progress",
    "revision_chain",
    "revision_events",
    "revoke_session",
    "session_scope",
    "set_change_listener",
    "stage_candidates",
    "undo",
    "update_campaign",
    "update_entity",
    "verify_login",
    "world_edges",
    "world_entities",
    "world_state",
]
